### ISSUE TITLE
NewNunchuk and ClassicControllerPro are not recognized

### ISSUE THREAD

**Issue by samuelhermann** [csBlueChip/FlipperZero_WiiEC#2]
Hello BlueChip,

As discussed on discord, I have latest revision for both NewNunchuk and ClassicControllerPro.
Their PID are indeed different from the one you have implemented.

Nunchuk                = 0x0000a4200000,
NewNunchuk            = 0xff00a4200000

ClassicController   = 0x0000a4200101,
ClassicControllerPro = 0x0100a4200101

I suggest to add additional PID in wii_ec.c

Thanks

**Comment by csBlueChip** [comment]
https://github.com/csBlueChip/FlipperZero_WiiEC/commit/d833473bd47846b815f2c2a91fd014808bee2f83

I have addressed the PID issue.

Also, looking at your photos (on Discord) and your video (on Youtube) I have tried to fix the problem with the ClassicPro joysticks. The problem is, there is no Factory Calibration Data in your controller [confirmed elsewhere online] - so I have made a change which will (should) force the FZ in to Software Calibration mode when a ClassicPro is connected ...you will need to Short-OK (on the FZ) to exit Software Calibration Mode.

Can you please check to see if these fixes work.

Thanks for all your help,
BC
