### ISSUE TITLE
Pressing LEFT on SPLASH

### ISSUE THREAD

**Issue by funkmaster-fl0w** [csBlueChip/FlipperZero_WiiEC#3]
Hi BlueChip!
Pressing left on the SPLASH screen seems to crash/reboot the flipper.

**Comment by csBlueChip** [comment]
Hey funkmaster-fl0w :)

Thanks for reporting that, much appreciated :)

There are actually three different paths to instantiating the SPLASH scene. I found an issue with one of them - which certainly caused a full on device reboot, followed by a "null pointer dereference" error.

The event timer is paused upon entering the SPLASH scene, and restarted on the way out. But one of the three paths failed to stop the timer - and if you call `furi_timer_start()` on a timer which is *already* started, rather than return `FuriStatusAlreadyRunning`, it causes the Flipper to reboot   "\\\_O_/"

Anyway. Hopefully this was the path you were using. And, if so, it is now fixed :)

Cheers,
BC
